{
 "title": "Pulled Pork",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Sensor 1",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select (CONCAT(date, \" \", time)) as time, temp1 from data ORDER by time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Sensor 2",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select (CONCAT(date, \" \", time)) as time, temp2 from data ORDER by time DESC LIMIT 1\n"
    }
   ]
  },
  {
   "title": "Battery Pct",
   "type": "stat",
   "description": "Battery level percentage",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select (CONCAT(date, \" \", time)) as time, bat from data ORDER by time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "iBBQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select UNIX_TIMESTAMP(CONCAT(date, \" \", time)) as time, temp1, temp2 from data;"
    }
   ]
  }
 ]
}